name: Uno
on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2

    - name: Run
      run: node index.js
      env: 
        GITHUB: ${{ toJson(github) }}

        