name: Uno
on: pull_request

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1

    - name: Run
      run: node index.js
      env: 
        COMMITS: ${{ toJson(github.event.pull_request.commits ) }}

